# 1. Strings and Dictionaries


__List Comprehension__ (instead of StringBuffer)

In [68]:
''.join(['abc%s_'%i for i in range(10)])

'abc0_abc1_abc2_abc3_abc4_abc5_abc6_abc7_abc8_abc9_'

__Dictionary__ (instead of HashMap)

collections.OrderedDict – A dictionary subclass that remembers the insertion order of keys added to the collection.

collections.ChainMap – Search multiple dictionaries as a single mapping.

In [7]:
from collections import OrderedDict
d = collections.OrderedDict(one=1, two=2, three=3)
d

OrderedDict([('one', 1), ('two', 2), ('three', 3)])

In [5]:
from collections import ChainMap
dict1 = {'one': 1, 'two': 2}
dict2 = {'three': 3, 'four': 4}
chain = ChainMap(dict1, dict2)
print(chain)
print(chain['three'])
print(chain['one'])

ChainMap({'one': 1, 'two': 2}, {'three': 3, 'four': 4})
3
1


Building in a List Comprehension manner

In [70]:
ch_dict = {ch:0 for ch in string.ascii_lowercase}
'a' in ch_dict

True

__Strings__

- ord, chr for chars
- lower(), upper()
- replace(' ', '')
- sort()

In [72]:
import string
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.digits)
print(string.whitespace)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789
 	



__NumPy Array__

Adding `A + B`

Multiplication `A.dot(B)`

Transpositioning `A.transpose()`


In [16]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)
print("A[1][2] =", A[1][2])
print("A[0] =", A[0])
print("A[:,0] =",A[:,0])
print(A.shape)

[[1 2 3]
 [3 4 5]]
A[1][2] = 5
A[0] = [1 2 3]
A[:,0] = [1 3]
(2, 3)


In [3]:
zarray = np.zeros((2, 3))
print(zarray)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(3, 4)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
A = np.arange(5)
print(A[:])   
print(A[::-1])

[0 1 2 3 4]
[4 3 2 1 0]


------

__1.1 Is Unique:__ Implement an algorithm to determine if a string has all unique characters. What if you
cannot use additional data structures?

One solution is to create an array of boolean values, where the flag at index i indicates whether character
i in the alphabet is contained in the string. The second time you see this character you can immediately
return false.
The time complexity for this code is O(n), where n is the length of the string. The space complexity is O(1).

- if the string is an ASCII string (128 or 256) or a Unicode string
- you can't form a string of 280 unique characters out of a 128-character alphabet

In [9]:
# O(n) complexity, O(1) space
def all_unique_ascii(s:str) -> bool:
    if len(s) > 128: 
        return False
    ch_dict = {}
    for ch in s:
        if ch not in ch_dict:
            ch_dict[ch] = True
        else:
            return False
    return True

In [25]:
# O(n) complexity, O(1) space, bit operations
def all_unique_chars(s:str) -> bool:
    if len(s) > 128: 
        return False
    checker = 0
    for ch in s:
        val = ord(ch) - ord('a')
        if (checker & (1 << val)) > 0 :
            return False
        checker |= (1 << val)
    return True

In [11]:
# O(n*log n) no extra space
def all_unique(s:str) -> bool:
    s = list(s)
    s.sort()
    for i in range(len(s) - 1):
        if s[i] == s[i+1]:
            return False
    return True

In [12]:
my_str1 = 'anrldkngowbd'
my_str2 = 'abcdefg'
my_str3 = ''
all_unique_ascii(my_str3)

True

__1.2 Check Permutation:__ Given two strings, write a method to decide if one is a permutation of the
other.

- if the permutation comparison is case sensitive
- if whitespace is significant

In [26]:
from typing import List, Any

# O(n*log n)
def is_permutation(fst: List[Any], snd: List[Any]) -> bool:
    if len(fst) != len(snd):
        return False
    fst.sort()
    snd.sort()
    for i in range(len(fst)):
        if fst[i] != snd[i]:
            return False
    return True

In [73]:
import string
def check_permutation(fst:str, snd:str) -> bool:
    if len(fst) != len(snd):
        return False
    ch_dict = {ch:0 for ch in string.ascii_lowercase}
    for ch in fst.lower():
        ch_dict[ch] += 1
    for ch in snd.lower():
        ch_dict[ch] -= 1
        if ch_dict[ch] < 0:
            return False
    return True

In [75]:
my_str1 = 'andrdld'
my_str2 = 'arndldd'
check_permutation('asd', 'asd')

True

__1.4 Palindrome Permutation:__ Given a string, write a function to check if it is a permutation of a palindrome. A palindrome is a word or phrase that is the same forwards and backwards. A permutation is a rearrangement of letters. The palindrome does not need to be limited to just dictionary words.

EXAMPLE

Input: Tact Coa

Output: True (permutations: "taco cat". "atco cta". etc.)

- not case sensitive
- whitespaces doesn't matter

A very elegant way to check that an integer has exactly one bit set to 1. We can check to see that a number has exactly one 1 because if we subtract 1 from it and then AND it with the new number, we should get 0.

00010000 - 1 = 00001111

00010000 & 00001111 = 0

In [43]:
# O(n) time, full dictionary
import string

def palindrome_per(s:str) -> bool:
    ch_dict = {ch:0 for ch in string.ascii_letters}
    for ch in s.replace(' ', '').lower():
        ch_dict[ch] += 1
    flag = False
    for ch in ch_dict.keys():
        if ch_dict[ch] % 2 == 1:
            if flag: 
                return False
            flag = True
    return True

In [80]:
# O(n) time, bitwise
def check_one(i:int) -> bool:
    return (i & (i - 1)) == 0

def is_palindrome(s:str) -> bool:
    letters = 0
    for ch in s.replace(' ', '').lower():
        letters ^= (1 << (ord(ch) - ord('a')))    
    return (letters == 0) or check_one(letters)

In [81]:
is_palindrome("Tact Coa")

True

__1.5 One Away:__ There are three types of edits that can be performed on strings: insert a character,
remove a character, or replace a character. Given two strings, write a function to check if they are
one edit (or zero edits) away.

In [5]:
def is_changed(fst: str, snd: str) -> bool:
    edit = False
    for i in range(len(fst)):
        if fst[i] != snd[i]:
            if edit: return False
            edit = True
    return True

def is_insert(fst: str, snd: str) -> bool:
    edit = False
    i = 0
    j = 0
    while i < len(fst) and j < len(snd):
        if fst[i] != snd[j]:
            if edit: return False
            j += 1
            edit = True
        else:    
            i += 1
            j += 1
    return True                    

def one_away(fst: str, snd: str) -> bool:
    if abs(len(fst) - len(snd)) > 1:
        return False
    if len(fst) == len(snd):
        return is_changed(fst, snd)
    else:
        if len(fst) < len(snd):
            return is_insert(fst, snd)
        else:
            return is_insert(snd, fst)

In [6]:
print(one_away('', ''))
print(one_away('abc', 'abc'))
print(one_away('abcd', 'abc'))
print(one_away('abc', 'abcd'))
print(one_away('adc', 'abc'))
print(one_away('abcdd', 'abc'))
print(one_away('ade', 'abc'))
print(one_away('abde', 'abc'))

True
True
True
True
True
False
False
False


__1.6 String Compression:__ Implement a method to perform basic string compression using the counts of repeated characters. For example, the string aabcccccaaa would become a2b1c5a3. If the "compressed" string would not become smaller than the original string, your method should return the original string. You can assume the string has only uppercase and lowercase letters (a - z).

- use `StringBuffer`
- first count the future length of the string, still be O(n)

In [6]:
import string

def str_compression(s: str) -> str:
    result = []
    prev_ch = s[0]
    count = 0
    for ch in s:
        if ch == prev_ch:
            count += 1
        else:
            result.append(prev_ch)
            result.append(str(count))
            prev_ch = ch
            count = 1
    result.append(prev_ch)
    result.append(str(count))
    return ''.join(result) if len(result) < len(s) else s        

In [7]:
str_compression('aaabbbcdddsscc')

'a3b3c1d3s2c2'

__1.8 Zero Matrix:__ Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column are set to 0.

Can be implemented without additional space, using e.g. first row and column as a storage.

In [21]:
import numpy as np

m = np.arange(16).reshape(4,4)
m[2,2] = 0
m[0,3] = 0
print(m)

[[ 0  1  2  0]
 [ 4  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]]


In [18]:
# O(n*m)
def zero_matrix(m):
    elements = []
    for i in range(m.shape[0]):
        for j in range(m.shape[1]):
            if m[i,j] == 0:
                elements.append((i,j))
    for (i, j) in elements:
        m[i, :] = 0
        m[:, j] = 0
    return m

In [23]:
# O(n*m), using sets
def zero_matr(m):
    rows = set([])
    columns = set([])
    for i in range(m.shape[0]):
        for j in range(m.shape[1]):
            if m[i,j] == 0:
                rows.add(i)
                columns.add(j)
    for i in rows:
        m[i, :] = 0
    for j in columns:
        m[:, j] = 0
    return m

In [24]:
new_m = zero_matr(m)

In [25]:
print(new_m)

[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0  0  0]
 [ 0 13  0  0]]


__1.9 String Rotation:__ Assume you have a method isSubstring which checks if one word is a substring of another. Given two strings, s1 and s2, write code to check if s2 is a rotation of s1 using only one call to isSubstring (e. g., "waterbottle " is a rotation of "erbottlewat").

x = wat, y = erbottle

waterbottle = xy

erbottlewat = yx

In [17]:
def rotation(fst:str, snd:str) -> bool:
    if len(fst) != len(snd):
        return False
    double = fst + fst
    return snd in double

In [18]:
rotation('waterbottle', 'erbottlewat')

True

In [20]:
rotation('sdf', 'dsf')

False

-----
# Linked Lists

__List__

- append() Adds an element at the end of the list
- clear() Removes all the elements from the list
- copy() Returns a copy of the list
- count() Returns the number of elements with the specified value
- index() Returns the index of the first element with the specified value
- insert() Adds an element at the specified position
- pop() Removes the element at the specified position
- remove() Removes the first item with the specified value
- reverse() Reverses the order of the list
- sort() Sorts the list

In [1]:
my_list = ['Hello', ', ', 'world']
my_list[0] = 'Hi'
my_list.append('!')
for x in my_list:
    print(x)

Hi
, 
world
!


In [26]:
class Node:
    def __init__(self, dataval=None):
        self.dataval = dataval
        self.nextval = None

class LinkedList:
    def __init__(self):
        self.headval = None

l = LinkedList()
l.headval = Node("Mon")
e2 = Node("Tue")
e3 = Node("Wed")
l.headval.nextval = e2
e2.nextval = e3

__2.1 Remove Dups:__ Write code to remove duplicates from an unsorted linked list.

FOLLOW UP: How would you solve this problem if a temporary buffer is not allowed?

- do we need to modify list? or can we create a new one? can just append to a new list
- do we need to save the order of elements? if not, can use convertion to set or numpy.unique

In [25]:
# O(n)
def remove_dups(uns_list):
    elements = set()
    idx = 0
    while idx < len(uns_list):
        if uns_list[idx] in elements:
            uns_list.pop(idx)
        else:
            elements.add(uns_list[idx])
            idx +=  1
    return uns_list  

In [26]:
remove_dups(list('asdnasdkfbs'))

['a', 's', 'd', 'n', 'k', 'f', 'b']

In [16]:
# o(n^2)
def remove_dups2(uns_list):
    idx = 0
    while idx < len(uns_list):
        runner = idx + 1
        while runner < len(uns_list):
            if uns_list[idx] == uns_list[runner]:
                uns_list.pop(runner)
            else:
                runner += 1
        idx += 1
    return uns_list

In [17]:
remove_dups2(list('asdnasdkfbs'))

['a', 's', 'd', 'n', 'k', 'f', 'b']

In [18]:
remove_dups2(list(''))

[]

In [19]:
remove_dups2(list('aaaaaaa'))

['a']

In [20]:
remove_dups2(list('absa'))

['a', 'b', 's']

In [27]:
import numpy as np
x = np.array(list('asdnasdkfbs')) 
print(np.unique(x)) 

['a' 'b' 'd' 'f' 'k' 'n' 's']


__2.2 Return Kth to Last:__ Implement an algorithm to find the kth to last element of a singly linked list.
Hints: #8, #25, #47, #6 7, # 726

104
Hints 670
Solutions 220

__2.3 Delete Middle Node:__ Implement an algorithm to delete a node in the middle (i.e., any node but
the first and last node, not necessarily the exact middle) of a singly linked list, given only access to
that node.
EXAMPLE
Input: the node c from the linked list a - >b- >c - >d ->e- >f
Result: nothing is returned, but the new linked list looks like a - >b- >d ->e- >f
Hints: #72

__2.4 Partition:__ Write code to partition a linked list around a value x, such that all nodes less than x come
before all nodes greater than or equal to x. lf x is contained within the list, the values of x only need
to be after the elements less than x (see below). The partition element x can appear anywhere in the
"right partition "; it does not need to appear between the left and right partitions.
EXAMPLE
`Input: 3 -> 5 -> 8 -> 5 -> 10 -> 2 -> 1 [partition = 5)
Output: 3 -> 1 -> 2 -> 10 -> 5 -> 5 -> 8`
Hints: #3, # 24

__2.5 Sum Lists:__ You have two numbers represented by a linked list, where each node contains a single
digit. The digits are stored in reverse order, such that the 1 's digit is at the head of the list. Write a
function that adds the two numbers and returns the sum as a linked list.
EXAMPLE
Input: (7-) 1 -) 6) + (5 -) 9 -) 2) . Thatis,617 + 295.
Output: 2 -) 1 -) 9. That is, 912 .
FOLLOW UP
Suppose the digits are stored in forward order. Repeat the above problem.
EXAMPLE
Input: (6 -) 1 -) 7) + (2 -) 9 -) 5) . Thatis,617 + 295.
Output: 9 -) 1 -) 2. That is, 912.
Hints: #7, #30, #71, #95, #109

__2.6 Palindrome:__ Implement a function to check if a linked list is a palindrome.
Hints: #5, #13, #29, #61, #101

__2.7 Intersection:__ Given two (singly) linked lists, determine if the two lists intersect. Return the inter-
secting node. Note that the intersection is defined based on reference, not value. That is, if the kth
node of the first linked list is the exact same node (by reference) as the jth node of the second
linked list, then they are intersecting.
Hints: #2 0, #45, #55, #65, #76, #93, #111, #120, #129

__2.8 Loop Detection:__ Given a circular linked list, implement an algorithm that returns the node at the
beginning of the loop.
DEFINI T ION
Circular linked list: A (corrupt) linked list in which a node's next pointer points to an earlier node, so
as to make a loop in the linked list.
EXAMPLE
Input: A -) B -) C -) 0 -) E - ) C[thesameCasearlierl
Output: C
Hints: # 50, #69, #83, #90

-----
# Bitwise Operations

&, |, ^, ~ << 

A very elegant way to __check that an integer has exactly one bit set to 1__. We can check to see that a number has exactly one 1 because if we subtract 1 from it and then AND it with the new number, we should get 0.

00010000 - 1 = 00001111

00010000 & 00001111 = 0


In [79]:
i = 1
(i & (i - 1)) == 0

True