# 1. Strings and Dictionaries


__List Comprehension__ (instead of StringBuffer)

In [68]:
''.join(['abc%s_'%i for i in range(10)])

'abc0_abc1_abc2_abc3_abc4_abc5_abc6_abc7_abc8_abc9_'

__Dictionary__ (instead of HashMap)

collections.OrderedDict – A dictionary subclass that remembers the insertion order of keys added to the collection.

collections.ChainMap – Search multiple dictionaries as a single mapping.

In [7]:
from collections import OrderedDict
d = collections.OrderedDict(one=1, two=2, three=3)
d

OrderedDict([('one', 1), ('two', 2), ('three', 3)])

In [5]:
from collections import ChainMap
dict1 = {'one': 1, 'two': 2}
dict2 = {'three': 3, 'four': 4}
chain = ChainMap(dict1, dict2)
print(chain)
print(chain['three'])
print(chain['one'])

ChainMap({'one': 1, 'two': 2}, {'three': 3, 'four': 4})
3
1


Building in a List Comprehension manner

In [70]:
import string
ch_dict = {ch:0 for ch in string.ascii_lowercase}
'a' in ch_dict

True

__Strings__

- ord, chr for chars
- lower(), upper()
- replace(' ', '')
- sort()

In [72]:
import string
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.digits)
print(string.whitespace)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789
 	



__NumPy Array__

Adding `A + B`

Multiplication `A.dot(B)`

Transpositioning `A.transpose()`


In [16]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)
print("A[1][2] =", A[1][2])
print("A[0] =", A[0])
print("A[:,0] =",A[:,0])
print(A.shape)

[[1 2 3]
 [3 4 5]]
A[1][2] = 5
A[0] = [1 2 3]
A[:,0] = [1 3]
(2, 3)


In [3]:
zarray = np.zeros((2, 3))
print(zarray)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(3, 4)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
A = np.arange(5)
print(A[:])   
print(A[::-1])

[0 1 2 3 4]
[4 3 2 1 0]


------

__1.1 Is Unique:__ Implement an algorithm to determine if a string has all unique characters. What if you
cannot use additional data structures?

One solution is to create an array of boolean values, where the flag at index i indicates whether character
i in the alphabet is contained in the string. The second time you see this character you can immediately
return false.
The time complexity for this code is O(n), where n is the length of the string. The space complexity is O(1).

- if the string is an ASCII string (128 or 256) or a Unicode string
- you can't form a string of 280 unique characters out of a 128-character alphabet

In [9]:
# O(n) complexity, O(1) space
def all_unique_ascii(s:str) -> bool:
    if len(s) > 128: 
        return False
    ch_dict = {}
    for ch in s:
        if ch not in ch_dict:
            ch_dict[ch] = True
        else:
            return False
    return True

In [25]:
# O(n) complexity, O(1) space, bit operations
def all_unique_chars(s:str) -> bool:
    if len(s) > 128: 
        return False
    checker = 0
    for ch in s:
        val = ord(ch) - ord('a')
        if (checker & (1 << val)) > 0 :
            return False
        checker |= (1 << val)
    return True

In [11]:
# O(n*log n) no extra space
def all_unique(s:str) -> bool:
    s = list(s)
    s.sort()
    for i in range(len(s) - 1):
        if s[i] == s[i+1]:
            return False
    return True

In [12]:
my_str1 = 'anrldkngowbd'
my_str2 = 'abcdefg'
my_str3 = ''
all_unique_ascii(my_str3)

True

__1.2 Check Permutation:__ Given two strings, write a method to decide if one is a permutation of the
other.

- if the permutation comparison is case sensitive
- if whitespace is significant

In [26]:
from typing import List, Any

# O(n*log n)
def is_permutation(fst: List[Any], snd: List[Any]) -> bool:
    if len(fst) != len(snd):
        return False
    fst.sort()
    snd.sort()
    for i in range(len(fst)):
        if fst[i] != snd[i]:
            return False
    return True

In [73]:
import string
def check_permutation(fst:str, snd:str) -> bool:
    if len(fst) != len(snd):
        return False
    ch_dict = {ch:0 for ch in string.ascii_lowercase}
    for ch in fst.lower():
        ch_dict[ch] += 1
    for ch in snd.lower():
        ch_dict[ch] -= 1
        if ch_dict[ch] < 0:
            return False
    return True

In [75]:
my_str1 = 'andrdld'
my_str2 = 'arndldd'
check_permutation('asd', 'asd')

True

__1.4 Palindrome Permutation:__ Given a string, write a function to check if it is a permutation of a palindrome. A palindrome is a word or phrase that is the same forwards and backwards. A permutation is a rearrangement of letters. The palindrome does not need to be limited to just dictionary words.

EXAMPLE

Input: Tact Coa

Output: True (permutations: "taco cat". "atco cta". etc.)

- not case sensitive
- whitespaces doesn't matter

A very elegant way to check that an integer has exactly one bit set to 1. We can check to see that a number has exactly one 1 because if we subtract 1 from it and then AND it with the new number, we should get 0.

00010000 - 1 = 00001111

00010000 & 00001111 = 0

In [43]:
# O(n) time, full dictionary
import string

def palindrome_per(s:str) -> bool:
    ch_dict = {ch:0 for ch in string.ascii_letters}
    for ch in s.replace(' ', '').lower():
        ch_dict[ch] += 1
    flag = False
    for ch in ch_dict.keys():
        if ch_dict[ch] % 2 == 1:
            if flag: 
                return False
            flag = True
    return True

In [80]:
# O(n) time, bitwise
def check_one(i:int) -> bool:
    return (i & (i - 1)) == 0

def is_palindrome(s:str) -> bool:
    letters = 0
    for ch in s.replace(' ', '').lower():
        letters ^= (1 << (ord(ch) - ord('a')))    
    return (letters == 0) or check_one(letters)

In [81]:
is_palindrome("Tact Coa")

True

__1.5 One Away:__ There are three types of edits that can be performed on strings: insert a character,
remove a character, or replace a character. Given two strings, write a function to check if they are
one edit (or zero edits) away.

In [5]:
def is_changed(fst: str, snd: str) -> bool:
    edit = False
    for i in range(len(fst)):
        if fst[i] != snd[i]:
            if edit: return False
            edit = True
    return True

def is_insert(fst: str, snd: str) -> bool:
    edit = False
    i = 0
    j = 0
    while i < len(fst) and j < len(snd):
        if fst[i] != snd[j]:
            if edit: return False
            j += 1
            edit = True
        else:    
            i += 1
            j += 1
    return True                    

def one_away(fst: str, snd: str) -> bool:
    if abs(len(fst) - len(snd)) > 1:
        return False
    if len(fst) == len(snd):
        return is_changed(fst, snd)
    else:
        if len(fst) < len(snd):
            return is_insert(fst, snd)
        else:
            return is_insert(snd, fst)

In [6]:
print(one_away('', ''))
print(one_away('abc', 'abc'))
print(one_away('abcd', 'abc'))
print(one_away('abc', 'abcd'))
print(one_away('adc', 'abc'))
print(one_away('abcdd', 'abc'))
print(one_away('ade', 'abc'))
print(one_away('abde', 'abc'))

True
True
True
True
True
False
False
False


__1.6 String Compression:__ Implement a method to perform basic string compression using the counts of repeated characters. For example, the string aabcccccaaa would become a2b1c5a3. If the "compressed" string would not become smaller than the original string, your method should return the original string. You can assume the string has only uppercase and lowercase letters (a - z).

- use `StringBuffer`
- first count the future length of the string, still be O(n)

In [6]:
import string

def str_compression(s: str) -> str:
    result = []
    prev_ch = s[0]
    count = 0
    for ch in s:
        if ch == prev_ch:
            count += 1
        else:
            result.append(prev_ch)
            result.append(str(count))
            prev_ch = ch
            count = 1
    result.append(prev_ch)
    result.append(str(count))
    return ''.join(result) if len(result) < len(s) else s        

In [7]:
str_compression('aaabbbcdddsscc')

'a3b3c1d3s2c2'

__1.8 Zero Matrix:__ Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column are set to 0.

Can be implemented without additional space, using e.g. first row and column as a storage.

In [21]:
import numpy as np

m = np.arange(16).reshape(4,4)
m[2,2] = 0
m[0,3] = 0
print(m)

[[ 0  1  2  0]
 [ 4  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]]


In [18]:
# O(n*m)
def zero_matrix(m):
    elements = []
    for i in range(m.shape[0]):
        for j in range(m.shape[1]):
            if m[i,j] == 0:
                elements.append((i,j))
    for (i, j) in elements:
        m[i, :] = 0
        m[:, j] = 0
    return m

In [23]:
# O(n*m), using sets
def zero_matr(m):
    rows = set([])
    columns = set([])
    for i in range(m.shape[0]):
        for j in range(m.shape[1]):
            if m[i,j] == 0:
                rows.add(i)
                columns.add(j)
    for i in rows:
        m[i, :] = 0
    for j in columns:
        m[:, j] = 0
    return m

In [24]:
new_m = zero_matr(m)

In [25]:
print(new_m)

[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0  0  0]
 [ 0 13  0  0]]


__1.9 String Rotation:__ Assume you have a method isSubstring which checks if one word is a substring of another. Given two strings, s1 and s2, write code to check if s2 is a rotation of s1 using only one call to isSubstring (e. g., "waterbottle " is a rotation of "erbottlewat").

x = wat, y = erbottle

waterbottle = xy

erbottlewat = yx

In [17]:
def rotation(fst:str, snd:str) -> bool:
    if len(fst) != len(snd):
        return False
    double = fst + fst
    return snd in double

In [18]:
rotation('waterbottle', 'erbottlewat')

True

In [20]:
rotation('sdf', 'dsf')

False

-----
# Linked Lists

__List__

- append(value) Adds an element at the end of the list
- clear() Removes all the elements from the list
- copy() Returns a copy of the list
- count(value) Returns the number of elements with the specified value
- index(value) Returns the index of the first element with the specified value
- insert(position, value) Adds an element at the specified position
- pop(position) Removes the element at the specified position, __without parameter__  removes and returns last value from the list 
- remove(value) Removes the first item with the specified value
- reverse() Reverses the order of the list
- sort() Sorts the list

In [1]:
my_list = ['Hello', ', ', 'world']
my_list[0] = 'Hi'
my_list.append('!')
for x in my_list:
    print(x)

Hi
, 
world
!


In [26]:
class Node:
    def __init__(self, dataval=None):
        self.dataval = dataval
        self.nextval = None

class LinkedList:
    def __init__(self):
        self.headval = None

l = LinkedList()
l.headval = Node("Mon")
e2 = Node("Tue")
e3 = Node("Wed")
l.headval.nextval = e2
e2.nextval = e3

__2.1 Remove Dups:__ Write code to remove duplicates from an unsorted linked list.

FOLLOW UP: How would you solve this problem if a temporary buffer is not allowed?

- do we need to modify list? or can we create a new one? can just append to a new list
- do we need to save the order of elements? if not, can use convertion to set or numpy.unique

In [1]:
# O(n)
def remove_dups(uns_list):
    elements = []
    for elem in uns_list:
        if elem not in elements:
            elements.append(elem)
    return elements

In [2]:
remove_dups(list('asdnasdkfbs'))

['a', 's', 'd', 'n', 'k', 'f', 'b']

In [16]:
# o(n^2)
def remove_dups2(uns_list):
    idx = 0
    while idx < len(uns_list):
        runner = idx + 1
        while runner < len(uns_list):
            if uns_list[idx] == uns_list[runner]:
                uns_list.pop(runner)
            else:
                runner += 1
        idx += 1
    return uns_list

In [17]:
remove_dups2(list('asdnasdkfbs'))

['a', 's', 'd', 'n', 'k', 'f', 'b']

In [18]:
remove_dups2(list(''))

[]

In [19]:
remove_dups2(list('aaaaaaa'))

['a']

In [20]:
remove_dups2(list('absa'))

['a', 'b', 's']

In [27]:
import numpy as np
x = np.array(list('asdnasdkfbs')) 
print(np.unique(x)) 

['a' 'b' 'd' 'f' 'k' 'n' 's']


__2.2 Return Kth to Last:__ Implement an algorithm to find the kth to last element of a singly linked list.

- first count the length, then go from the begginning O(n)
- use two pointers, send the first k elements prior to the second O(n)

In [4]:
def getKth(my_list, k):
    return my_list[-k]

In [5]:
x = list('asdnasdkfbs')
getKth(x, 3)

'f'

__2.3 Delete Middle Node:__ Implement an algorithm to delete a node in the middle (i.e., any node but the first and last node, not necessarily the exact middle) of a singly linked list, given only access to that node.

EXAMPLE

Input: the node c from the linked list a -> b -> c -> d -> e -> f

Result: nothing is returned, but the new linked list looks like a -> b -> d -> e -> f

__Solution:__ copy rest of the list

In [3]:
x = list('asdnasdkfbs')
x.pop(-3)
x

['a', 's', 'd', 'n', 'a', 's', 'd', 'k', 'b', 's']

__2.4 Partition:__ Write code to partition a linked list around a value x, such that all nodes less than x come before all nodes greater than or equal to x. lf x is contained within the list, the values of x only need to be after the elements less than x (see below). The partition element x can appear anywhere in the "right partition"; it does not need to appear between the left and right partitions.

EXAMPLE

`Input: 3 -> 5 -> 8 -> 5 -> 10 -> 2 -> 1 [partition = 5]
Output: 3 -> 1 -> 2 -> 10 -> 5 -> 5 -> 8`

- using sort() gives result
- in Java is better to maintain 2 lists, 3 pointers in total would be enough
- can be easier to create only one new list (add smaller as a head, and bigger at the tail)

In [4]:
x = [3, 5, 8, 5, 10, 2, 1]
x.sort()
x

[1, 2, 3, 5, 5, 8, 10]

In [10]:
# O(n)
def partition(my_list, p):
    result = []
    for x in my_list:
        if x < p:
            result.insert(0, x)
        else:
            result.append(x)
    return result

In [11]:
partition([3, 5, 8, 5, 10, 2, 1], 5)

[1, 2, 3, 5, 8, 5, 10]

__2.5 Sum Lists:__ You have two numbers represented by a linked list, where each node contains a single digit. The digits are stored in reverse order, such that the 1's digit is at the head of the list. Write a function that adds the two numbers and returns the sum as a linked list.

EXAMPLE

Input: `7 -> 1 -> 6 + 5 -> 9 -> 2` That is, 617 + 295.

Output: `2 -> 1 -> 9` That is, 912.

FOLLOW UP
Suppose the digits are stored in forward order. Repeat the above problem.

EXAMPLE

Input: `6 -> 1 -> 7 + 2 -> 9 -> 5` That is, 617 + 295.

Output: `9 -> 1 -> 2` That is, 912.

- the first one can be done iteratively
- the second is easier solved recursively, if add '0000' at the beginning of the shorter list

In [15]:
def sum_from_end(fst, snd):
    lng = fst if len(fst) >= len(snd) else snd
    sml = fst if len(fst) < len(snd) else snd
    i = 0
    result = []
    prev = 0
    while i < len(sml):
        s = lng[i] + sml[i] + prev
        result.append(s % 10)
        prev = s // 10
        i +=1
    while i < len(lng):
        s = lng[i] + prev
        result.append(s % 10)
        prev = s // 10
        i +=1
    if prev > 0:
        result.append(prev)
    return result

In [16]:
sum_from_end([7, 1, 6], [5, 9, 2])

[2, 1, 9]

In [17]:
sum_from_end([], [5, 9, 2])

[5, 9, 2]

In [18]:
sum_from_end([0, 0, 0, 1], [5, 9, 2])

[5, 9, 2, 1]

In [19]:
sum_from_end([9, 7, 8], [6, 8, 5])

[5, 6, 4, 1]

__2.6 Palindrome:__ Implement a function to check if a linked list is a palindrome.

- while counting length, reverse a copy of list
- compare two lists from the beginning up to the middle point
- if we don't know the length of the list, use runner technique to reach the middle, and save elements to stack (list, use pop())

In [7]:
def palindrome(my_list) -> bool:
    i = 0
    for i in range(len(my_list) // 2):
        if my_list[i] != my_list[-i-1]:
            return False
    return True

In [8]:
palindrome([])

True

In [9]:
palindrome([1, 1])

True

In [10]:
palindrome([1, 2, 3, 2, 1])

True

In [11]:
palindrome([1, 2, 3, 3, 2, 1])

True

In [12]:
palindrome([1, 2, 3, 4, 2, 1])

False

__2.7 Intersection:__ Given two (singly) linked lists, determine if the two lists intersect. Return the intersecting node. Note that the intersection is defined based on reference, not value. That is, if the kth node of the first linked list is the exact same node (by reference) as the jth node of the second linked list, then they are intersecting.

- since by reference, all the rest nodes must be the same
- comparing from the end, last node must be equal
- if length is known, can compare from the beginning

__2.8 Loop Detection:__ Given a circular linked list, implement an algorithm that returns the node at the beginning of the loop.

DEFINITION

Circular linked list: A (corrupt) linked list in which a node's next pointer points to an earlier node, so as to make a loop in the linked list.

EXAMPLE

Input: A -> B -> C -> D -> E -> C (the same C as earlier)

Output: C

- runner technique, if there is a loop, once meet

-----
# Stacks and Queues

__Stack__ can be simulated wth the list:

 - pop(): Remove the top item from the stack, `[1, 2].pop()`
 - push(item): Add an item to the top of the stack, `[1].append(2)`
 - peek(): Return the top of the stack, `[1, 2][-1]`
 - isEmpty(): Return true if and only if the stack is empty, `not []`

__OR__ can use `class queue.LifoQueue(maxsize)`

In [2]:
x = [1, 2]
y = x.pop()
print(x)
print(y)

[1]
2


In [5]:
x = [1]
y = x.append(2)
print(x)
print(y)

[1, 2]
None


In [6]:
[1, 2][-1]

2

In [1]:
not []

True

__Queue__ is implemented in a module `queue`, `class queue.Queue(maxsize)`

If maxsize == 0, then endless queue.

- add(item): Add an item to the end of the list, `put(item)`
- remove(): Remove the first item in the list, `get()`
- peek(): Return the top of the queue.
- isEmpty(): Return true if and only if the queue is empty, `empty()`

`class queue.PriorityQueue(maxsize): (priority, data)`

In [1]:
from queue import Queue
q = Queue()
 
q.put('eat')
q.put('sleep')
q.put('code')
 
print(q.get())
print(q.get())
print(q.get())
 
# error empty
# q.get_nowait()
# endless waiting
# q.get() 

eat
sleep
code


__3.1 Three in One:__ Describe how you could use a single array to implement three stacks.

- divide in three, keep links to the top.
- divide in three, if not enough space, then shift

__3.2 Stack Min:__ How would you design a stack which, in addition to push and pop, has a function min which returns the minimum element? Push, pop and min should all operate in O(1) time.

- keep second stack of mins

In [12]:
class Stack:

    def __init__(self):
        self._data = []
        self._min = [] # stack of mins
        
    def min(self):
        if len(self._min) > 0:
            return self._min[-1]
        return None 
    
    def peek(self):
        if len(self._data) > 0:
            return self._data[-1]
        return None
    
    def push(self, x):
        self._data.append(x)
        if (self.min() is None)  or (x <= self.min()):
            self._min.append(x)
        
    def pop(self):
        if len(self._data) > 0:
            x = self._data.pop() 
            if self.min() == x:
                self._min.pop() 
            return x
    
    def isEmpty(self):
        return not bool(self._data)

In [13]:
s = Stack()
s.push(2)
s.push(1)
print(s.isEmpty())
print('min %s' % s.min())
print('on top %s' % s.peek())
print('pop %s' % s.pop())
print('min %s' % s.min())
print('pop %s' % s.pop())
print('min %s' % s.min())
print(s.isEmpty())

False
min 1
on top 1
pop 1
min 2
pop 2
min None
True


__3.3 Stack of Plates:__ Imagine a (literal) stack of plates. If the stack gets too high, it might topple. Therefore, in real life, we would likely start a new stack when the previous stack exceeds some threshold. Implement a data structure SetOfStacks that mimics this. SetOfStacks should be composed of several stacks and should create a new stack once the previous one exceeds capacity. `SetOfStacks.push()` and `SetOfStacks.pop()` should behave identically to a single stack (that is, pop() should return the same values as it would if there were just a single stack).

FOLLOW UP
Implement a function popAt(int index) which performs a pop operation on a specific sub-stack.

- could be implemented with a rollover approach, without empty stacks in the middle

In [59]:
from typing import Optional

class Stack:
    def __init__(self, maxsize: int) -> None:
        self._data = []
        self._size = 0
        self.MAXSIZE = maxsize
        
    def push(self, value:int) -> bool:
        if self._size < self.MAXSIZE:
            self._data.append(value)
            self._size += 1
            return True
        else:
            return False
    
    def pop(self) -> Optional[int]:
        if self._data:
            self._size -= 1 
            return self._data.pop()
        else:
            return None

class SetOfStack:
    
    def __init__(self, maxsize:int) -> None:
        if maxsize <= 0:
            raise KeyError('Size must be greater than 0')
        self._stacks = []
        self.MAXSIZE = maxsize
        
    def push(self, value:int) -> bool:
        if (not self._stacks) or (not self._stacks[-1].push(value)):
            self._stacks.append(Stack(self.MAXSIZE))
            self._stacks[-1].push(value)
        
    def pop(self) -> Optional[int]:
        value = self._stacks[-1].pop() if self._stacks else None
        while (value is None) and (len(self._stacks) > 0):
            self._stacks.pop()
            if self._stacks:
                value = self._stacks[-1].pop()
        return value
    
    def popAt(self, index: int) -> Optional[int]:
        if len(self._stacks) > index:
            return self._stacks[index].pop()
        else:
            return None

In [63]:
plates = SetOfStack(3)
for i in range(8):
    plates.push(i)

In [64]:
plates.popAt(1)

5

In [65]:
for i in range(10):
    print(plates.pop())

7
6
4
3
2
1
0
None
None
None


__3.4 Queue via Stacks:__ Implement a MyQueue class which implements a queue using two stacks.

- from time to time, push all elements into another stack, thus providing a reverse order

In [25]:
from typing import Optional

class Stack:
    def __init__(self) -> None:
        self._data = []
        
    def push(self, value:int) -> None:
        self._data.append(value)
            
    def pop(self) -> Optional[int]:
        if self._data:
            return self._data.pop()
    
    def isEmpty(self) -> bool:
        return not self._data
            
class MyQueue:
    def __init__(self) -> None:
        self._newest = Stack()
        self._oldest = Stack()
        
    def _shift(self) -> None:
        if self._oldest.isEmpty():
            while not self._newest.isEmpty():
                self._oldest.push(self._newest.pop())
        
    def add(self, value:int) -> None:
        self._newest.push(value)
        
    def remove(self) -> Optional[int]:
        self._shift()
        return self._oldest.pop()
        

In [34]:
q = MyQueue()
for i in range(5):
    q.add(i)

In [35]:
for i in range(3):
    print(q.remove())

0
1
2


In [36]:
for i in range(5, 12):
    q.add(i)

In [37]:
for i in range(10):
    print(q.remove())

3
4
5
6
7
8
9
10
11
None


__3.5 Sort Stack:__ Write a program to sort a stack such that the smallest items are on the top. You can use an additional temporary stack, but you may not copy the elements into any other data structure (such as an array). The stack supports the following operations: push, pop, peek, and isEmpty.

- modification of insertion sort
- use original Stack as an additional storage
- in Python can be used a sort function (reverse = True)

In [8]:
from typing import Optional

class Stack:
    def __init__(self) -> None:
        self._data = []
        
    def peek(self) -> Optional[int]:
        if self._data:
            return self._data[-1]
        
    def push(self, value:int) -> None:
        self._data.append(value)
            
    def pop(self) -> Optional[int]:
        if self._data:
            return self._data.pop()
    
    def isEmpty(self) -> bool:
        return not self._data
    
    def __str__(self) -> str:
        return str(self._data)

In [9]:
def findPlace(e:int, s: Stack, t: Stack) -> (Stack, Stack):
    i = 0
    while (t.peek() is not None) and (e < t.peek()):
        s.push(t.pop())
        i += 1
    t.push(e)
    for j in range(i):
        t.push(s.pop())
    return s, t

def sort(s: Stack) -> Stack:
    t = Stack()
    while not s.isEmpty():
        s, t = findPlace(s.pop(), s, t)
        print('source %s' % s)
        print('sink %s' % t)
    while not t.isEmpty():
        s.push(t.pop())
    return s

In [10]:
s = Stack()
for i in [3, 2, 1, 5, 7]:
    s.push(i)
print(s)

[3, 2, 1, 5, 7]


In [11]:
t = sort(s)
print(t)

source [3, 2, 1, 5]
sink [7]
source [3, 2, 1]
sink [5, 7]
source [3, 2]
sink [1, 5, 7]
source [3]
sink [1, 2, 5, 7]
source []
sink [1, 2, 3, 5, 7]
[7, 5, 3, 2, 1]


In [12]:
s = Stack()
for i in range(7):
    s.push(i)
t = sort(s)
print(t)

source [0, 1, 2, 3, 4, 5]
sink [6]
source [0, 1, 2, 3, 4]
sink [5, 6]
source [0, 1, 2, 3]
sink [4, 5, 6]
source [0, 1, 2]
sink [3, 4, 5, 6]
source [0, 1]
sink [2, 3, 4, 5, 6]
source [0]
sink [1, 2, 3, 4, 5, 6]
source []
sink [0, 1, 2, 3, 4, 5, 6]
[6, 5, 4, 3, 2, 1, 0]


In [5]:
t = [3, 2, 1, 5, 7]
t.sort(reverse = True)
t

[7, 5, 3, 2, 1]

__3.6 Animal Shelter:__ An animal shelter, which holds only dogs and cats, operates on a strictly "first in, first out" basis. People must adopt either the "oldest" (based on arrival time) of all animals at the shelter, or they can select whether they would prefer a dog or a cat (and will receive the oldest animal of that type). They cannot select which specific animal they would like. Create the data structures to
maintain this system and implement operations such as enqueue, dequeueAny, dequeueDog, and dequeueCat. You may use the built-in Linked List data structure.

In [14]:
from typing import Optional

class Shelter:
    def __init__(self) -> None:
        self._cats = []
        self._dogs = []
        self._count = 0
        
    def enqueue(self, name:str, animal:str) -> bool:
        if animal == 'cat':
            self._cats.append((name, self._count))
        elif animal == 'dog':
            self._dogs.append((name, self._count))
        else:
            return False
        self._count += 1
        return True
    
    def dequeueAny(self) -> Optional[str]:
        c = self._cats[0] if self._cats else None
        d = self._dogs[0] if self._dogs else None
        name = None
        if (c is None) and (d is not None):
            name, _ = self._dogs.pop(0)
        elif (d is None) and (c is not None):
            name, _ = self._cats.pop(0)
        elif (c is not None) and (d is not None):
            name, _ = self._cats.pop(0) if c[1] < d[1] else self._dogs.pop(0)
        return name
        
    def dequeueCat(self) -> Optional[str]:
        if not self._cats:
            return None
        return self._cats.pop(0)[0]
            
    def dequeueDog(self) -> Optional[str]:   
        if not self._dogs:
            return None
        return self._dogs.pop(0)[0]

In [15]:
s = Shelter()
s.enqueue('Kitty', 'cat')
s.enqueue('Carol', 'cat')
s.enqueue('Boxer', 'dog')
s.enqueue('Robby', 'dog')
s.enqueue('Alex', 'cat')

True

In [16]:
s.dequeueAny()

'Kitty'

In [17]:
s.dequeueDog()

'Boxer'

In [18]:
s.dequeueCat()

'Carol'

In [19]:
s.dequeueAny()

'Robby'

In [20]:
s.dequeueDog()

---
# Trees  and Graphs

Need to be distinguished:
- Tree
- Binary Tree
- Binary Search Tree
- Complete Binary Tree
- Full Binary Tree
- Perfect Binary Tree

112
Hints 670
Solutions 253

### Tree implementation

In [42]:
class Node:

    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None
        

def inorder(root):
    if root is not None:
        inorder(root.left)
        print(root.key)
        inorder(root.right)
        
def insert(root, key):
    if root is None:
        return Node(key)
    if key < root.key:
        root.left = insert(root.left, key)
    elif key > root.key:
        root.right = insert(root.right, key)
    return root

def maxValueNode(root):
    current = root
    while current.right is not None:
        current = current.right
    return current
        
def remove(root, key):
    if root is None:
        return root
    
    if key < root.key:
        root.left = remove(root.left, key)
    elif key > root.key:
        root.right = remove(root.right, key)
    else:
        if root.left is None:
            temp = root.right
            root = None
            return temp
        if root.right is None:
            temp = root.left
            root = None
            return temp
        
        temp = maxValueNode(root.left)
        root.key = temp.key
        root.left = remove(root.left, temp.key)  
  
    return root  

In [44]:
root = None
root = insert(root, 10)
root = insert(root, 5)
root = insert(root, 3)
root = insert(root, 8)
root = insert(root, 15)
root = insert(root, 18)
root = insert(root, 13)

inorder(root)

3
5
8
10
13
15
18


In [45]:
remove(root, 13)
inorder(root)

3
5
8
10
15
18


remove(root, 15)
inorder(root)

In [47]:
remove(root, 5)
inorder(root)

3
8
10
18


In [48]:
remove(root, 10)
inorder(root)

3
8
18


### Min-heap implementation (over list)

- (i -1) / 2 returns parent node.
- (2 * i) + 1 returns left child node.
- (2 * i) + 2 returns right child node

extractMin and insert takes O(log n)

In [1]:
import heapq 
  
l = [7, 4, 50, 55, 90, 87, 80] 
  
# convert list in heap at place
heapq.heapify(l) 
print(list(l)) 
  
# add new element
heapq.heappush(l, 10) 
print(list(l)) 
  
# get element
print(heapq.heappop(l)) 
print(list(l)) 

[4, 7, 50, 55, 90, 87, 80]
[4, 7, 50, 10, 90, 87, 80, 55]
4
[7, 10, 50, 55, 90, 87, 80]


In [8]:
class minheap:
    
    def __init__(self) -> None:
        self.data = []
        self.size = 0
        
    def swap(self, fpos: int, spos: int) -> None:
        self.data[spos], self.data[fpos] = self.data[fpos], self.data[spos]
        
    def parent(self, pos: int) -> int: 
        return (pos - 1)//2
  
    def leftChild(self, pos): 
        return 2*pos + 1 
  
    def rightChild(self, pos): 
        return 2*pos + 2
  
    def isLeaf(self, pos): 
        if pos >= (self.size//2) and pos <= self.size: 
            return True
        return False
    
    def show(self) -> str:
        return self.data
    
    def insert(self, element: int): 
        self.data.append(element)
        current = self.size
        self.size += 1
        
        while self.data[current] < self.data[self.parent(current)]: 
            self.swap(current, self.parent(current)) 
            current = self.parent(current) 
  
    def minHeapify(self, pos: int):
        if not self.isLeaf(pos):
            lc = self.leftChild(pos)
            rc = self.rightChild(pos)
            if (self.data[pos] > self.data[lc]) or (self.data[pos] > self.data[rc]):
                if self.data[lc] < self.data[rc]:
                    self.swap(pos, lc)
                    self.minHeapify(lc)
                else:
                    self.swap(pos, rc)
                    self.minHeapify(rc)

    def get(self) -> int:
        self.swap(0, self.size - 1)
        result = self.data.pop()
        self.size -= 1
        self.minHeapify(0)
        return result

In [9]:
h = minheap()
h.insert(4)
h.insert(50)
h.insert(7)
h.insert(55)
h.insert(90)
h.insert(87)
h.show()

[4, 50, 7, 55, 90, 87]

In [10]:
h.insert(10)
h.insert(80)
h.show()

[4, 50, 7, 55, 90, 87, 10, 80]

In [11]:
h.get()

4

In [12]:
h.show()

[7, 50, 10, 55, 90, 87, 80]

__4.2 Minimal Tree:__ Given a sorted (increasing order) array with unique integer elements, write an algorithm to create a binary search tree with minimal height.

In [7]:
class Node:

    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None
        

def inorder(root):
    if root is not None:
        inorder(root.left)
        print(root.key)
        inorder(root.right)
        
def insertAll(keys):
    n = len(keys)
    if n == 0:
        return None
    elif n == 1:
        return Node(keys[0])
    else:
        i = n // 2
        root = Node(keys[i])
        root.left = insertAll(keys[0:i])
        root.right = insertAll(keys[i+1:])
        return root

In [8]:
l = [1, 3, 5, 6, 7]
r = insertAll(l)
inorder(r)

1
3
5
6
7


__4.5 Validate BST:__ Implement a function to check if a binary tree is a binary search tree.

- for case without duplicates in-order will get an increasing sequence
- (min, max) approach will work in either way

In [19]:
class Node:

    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None
        

def inorder(root):
    if root is not None:
        inorder(root.left)
        print(root.key)
        inorder(root.right)
        
def insert(root, key):
    if root is None:
        return Node(key)
    if key < root.key:
        root.left = insert(root.left, key)
    elif key > root.key:
        root.right = insert(root.right, key)
    return root

        
def insert_not(root, key):
    if root is None:
        return Node(key)
    root.right = insert(root.right, key)
    return root

In [29]:
import sys
last_seen = -1 * sys.maxsize

def validate_bst(root: Node) -> bool:
    flag = True
    global last_seen 
    if root is None:
        return flag
    flag &= validate_bst(root.left)
    flag &= (root.key >= last_seen)
    last_seen = root.key
    flag &= validate_bst(root.right)
    return flag

In [36]:
import sys

def validate_bst2(root: Node, key_min:int, key_max:int) -> bool:
    if root is None:
        return True
    if (root.key >= key_max) or (root.key <= key_min):
        return False
    return validate_bst2(root.left, key_min, 
                         root.key) and validate_bst2(root.right, 
                                                     root.key, key_max) 
    
def validate_call(root:Node) -> bool:
    return validate_bst2(root, -1 * sys.maxsize, sys.maxsize)
    

In [37]:
root = None
root = insert(root, 10)
root = insert(root, 5)
root = insert(root, 3)
root = insert(root, 8)
root = insert(root, 15)
root = insert(root, 18)
root = insert(root, 13)

inorder(root)

3
5
8
10
13
15
18


In [31]:
validate_bst(root)

True

In [38]:
validate_call(root)

True

In [39]:
root = None
root = insert_not(root, 8)
root = insert_not(root, 3)
root = insert_not(root, 4)
root = insert_not(root, 6)

inorder(root)

8
3
4
6


In [33]:
validate_bst(root)

False

In [40]:
validate_call(root)

False

__4.3 List of Depths:__ Given a binary tree, design an algorithm which creates a linked list of all the nodes at each depth (e.g., if you have a tree with depth 0, you' ll have 0 linked lists).

Hints: #107, #123, #135

__4.4 Check Balanced:__ Implement a function to check if a binary tree is balanced. For the purposes of this question, a balanced tree is defined to be a tree such that the heights of the two subtrees of any node never differ by more than one.

Hints: #27, #33, #49 , #105 , #124

__4.1 Route Between Nodes:__ Given a directed graph, design an algorithm to find out whether there is a
route between two nodes.

Hints: #127

__4.6 Successor:__ Write an algorithm to find the "next" node (i.e., in-order successor ) of a given node in a binary search tree. You may assume that each node has a link to its parent.

Hints: #79, #91

__4.7 Build Order:__ You are given a list of projects and a list of dependencies (which is a list of pairs of projects, where the second project is dependent on the first project ). All of a project's dependencies must be built before the project is . Find a build order that will allow the projects to be built. If there is no valid build order, return an error.

EXAMPLE

projects: a, b, c, d, e, f

dependencies: (a, d), (f, b), (b, d), (f, a), (d, c)

Output: f, e, a, b, d, c

Hints: #26 , #47, #60 , #85 , #125, #133

__4.8 First Common Ancestor:__ Design an algorithm and write code to find the first common ancestor of two nodes in a binary tree. Avoid storing additional nodes in a data structure. 

NOTE: This is not necessarily a binary search tree.

Hints: #10 , #16, #28 , #36, #46 , #70 , #80, #96

__4.9 BST Sequences:__ A binary search tree was created by traversing through an array from left to right and inserting each element. Given a binary search tree with distinct elements, print all possible arrays that could have led to this tree.

EXAMPLE

Output: {2, 1, 3} , {2, 3, 1}

Hints: #39 , #48 , #66 , #82

__4.10 Check Subtree:__ Tl and T2 are two very large binary trees, with Tl much bigger than T2. Create an algorithm to determine if T2 is a subtree of Tl. A tree T2 is a subtree ofTi if there exists a node n in Ti such that the subtree of n is identical to T2. That is, if you cut off the tree at node n, the two trees would be identical.

Hints: #4, #11, #18, #31, #37

__4.11 Random Node:__ You are implementing a binary tree class from scratch which, in addition to insert, find, and delete, has a method getRandomNode() which returns a random node from the tree. All nodes should be equally likely to be chosen. Design and implement an algorithm
for getRandomNode, and explain how you would implement the rest of the methods.

Hints: #42, #54, #62, #75, #89, #99, #112 , #119

__4.12 Paths with Sum:__ You are given a binary tree in which each node contains an integer value (which might be positive or negative). Design an algorithm to count the number of paths that sum to a given value. The path does not need to start or end at the root or a leaf, but it must go downwards (traveling only from parent nodes to child nodes).

Hints: #6, #14, #52, #68, #77, #87, #94, #103, #108, #115

-----
# Bitwise Operations

&, |, ^, ~ << 

A very elegant way to __check that an integer has exactly one bit set to 1__. We can check to see that a number has exactly one 1 because if we subtract 1 from it and then AND it with the new number, we should get 0.

00010000 - 1 = 00001111

00010000 & 00001111 = 0


In [79]:
i = 1
(i & (i - 1)) == 0

True